[gitalk]
src = "https://giscus.app/client.js"
repo = "kurisaW/Gitalk"
repo_id = "Gitalk"
category = "[General]"
category_id = "[Blog_disscussion]"
mapping = "pathname"
strict = false
reactions_enabled = true
emit_metadata = false
input_position = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"
crossorigin = "anonymous"