# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kurisaW/kurisaW.github.io"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/KurisaWhh"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "csdn"
name = "CSDN"
url = "https://blog.csdn.net/qq_56914146?spm=1000.2115.3001.5343"

[social.params]
icon = "brand-csdn"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:yifang.wangyq@foxmail.com"

[social.params]
icon = "brand-email"

[[social]]
identifier = "Wechat"
name = "wechat"
url = "https://raw.githubusercontent.com/kurisaW/picbed/main/img/202302121550487.png"

[social.params]
icon = "brand-wechat"

[[social]]
identifier = "Chatbot"
name = "chatbot"
url = "https://heybot.thesamur.ai/heybot/embed?id=KJOTl99PQ51EgoOPDa9h9buZpBHzCtQI"

[social.params]
icon = "brand-chatbot"
