name: Update Blog Diary

on:
  push:
    branches: [ master ]
  delete:
    branches: [ master ]
  create:
    branches: [ master ]
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pip install pyyaml
        
    - name: Generate diary
      run: |  
        python .github/scripts/generate_readme.py
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update blog diary"
        git push
